import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "ISLAMIQUE NUANCE DE MARRON",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
  },
  {
    id: "2",
    name: "Cadre volume - orange marron beige abstrait",
    price: 3800,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
  },
  {
    id: "3",
    name: "Islamique dor fond marbre",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
  },
  {
    id: "4",
    name: "Automne vibes",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
  },
  {
    id: "5",
    name: "Botanique rose",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "6",
    name: "Branche d'arbre Gold",
    price: 3000,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
  },
  {
    id: "7",
    name: "Trio-kallimini -cand ( modèle mixte clai )",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
  },
  {
    id: "8",
    name: "Botanique beige vert",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "TOP VENTE",
  },
  {
    id: "9",
    name: "Abstrait Montagne beige Noir",
    price: 4800,
    image: "/placeholder.svg?height=400&width=400",
    badge: "TOP VENTE",
  },
  {
    id: "10",
    name: "The Trend Node",
    price: 3800,
    image: "/placeholder.svg?height=400&width=400",
    badge: "TOP VENTE",
  },
  {
    id: "11",
    name: "Mandala Marron TOILE",
    price: 3200,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "12",
    name: "Plume Bleu",
    price: 4400,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "13",
    name: "Botanique marron vert",
    price: 4800,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "14",
    name: "Flower beige esthétie",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
  },
  {
    id: "15",
    name: "Marron minimaliste line",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "16",
    name: "Boho Vert",
    price: 4800,
    image: "/placeholder.svg?height=400&width=400",
  },
]
