import type { Product } from "@/components/product-card"

export const products: Product[] = [
  {
    id: "1",
    name: "ISLAMIQUE NUANCE DE MARRON",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
    categories: ["islamique", "marron", "grand-tableaux"],
  },
  {
    id: "2",
    name: "Cadre volume - orange marron beige abstrait",
    price: 3800,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
    categories: ["abstrait", "orange", "marron", "beige"],
  },
  {
    id: "3",
    name: "Islamique dor fond marbre",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
    categories: ["islamique", "dore", "marbre", "grand-tableaux"],
  },
  {
    id: "4",
    name: "Automne vibes",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
    categories: ["automne", "moderne", "grand-tableaux"],
  },
  {
    id: "5",
    name: "Botanique rose",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    categories: ["botanique", "rose", "grand-tableaux"],
  },
  {
    id: "6",
    name: "Branche d'arbre Gold",
    price: 3000,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
    categories: ["botanique", "dore", "grand-tableaux"],
  },
  {
    id: "7",
    name: "Trio-kallimini -cand ( modèle mixte clai )",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
    categories: ["moderne", "minimaliste", "grand-tableaux"],
  },
  {
    id: "8",
    name: "Botanique beige vert",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "TOP VENTE",
    categories: ["botanique", "beige", "vert", "grand-tableaux"],
  },
  {
    id: "9",
    name: "Abstrait Montagne beige Noir",
    price: 4800,
    image: "/placeholder.svg?height=400&width=400",
    badge: "TOP VENTE",
    categories: ["abstrait", "montagne", "beige", "noir", "grand-tableaux"],
  },
  {
    id: "10",
    name: "The Trend Node",
    price: 3800,
    image: "/placeholder.svg?height=400&width=400",
    badge: "TOP VENTE",
    categories: ["moderne", "minimaliste", "grand-tableaux"],
  },
  {
    id: "11",
    name: "Mandala Marron TOILE",
    price: 3200,
    image: "/placeholder.svg?height=400&width=400",
    categories: ["mandala", "marron", "grand-tableaux"],
  },
  {
    id: "12",
    name: "Plume Bleu",
    price: 4400,
    image: "/placeholder.svg?height=400&width=400",
    categories: ["plume", "bleu", "grand-tableaux"],
  },
  {
    id: "13",
    name: "Botanique marron vert",
    price: 4800,
    image: "/placeholder.svg?height=400&width=400",
    categories: ["botanique", "marron", "vert", "grand-tableaux"],
  },
  {
    id: "14",
    name: "Flower beige esthétie",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    badge: "NOUVEAU",
    categories: ["fleur", "beige", "grand-tableaux"],
  },
  {
    id: "15",
    name: "Marron minimaliste line",
    price: 3900,
    image: "/placeholder.svg?height=400&width=400",
    categories: ["minimaliste", "marron", "grand-tableaux"],
  },
  {
    id: "16",
    name: "Boho Vert",
    price: 4800,
    image: "/placeholder.svg?height=400&width=400",
    categories: ["boho", "vert", "grand-tableaux"],
  },
]
